# Generated by Django 3.1.3 on 2020-11-11 12:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('lembrete', models.CharField(max_length=50)),
                ('date_lembrete', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_receita', models.ImageField(blank=True, upload_to='foto/%d/%m/%m/%y/')),
                ('feito', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
