# Generated by Django 3.1.3 on 2020-11-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201111_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%m/%y/'),
        ),
    ]
