# Generated by Django 3.1.3 on 2020-11-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201111_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='foto_perfil',
        ),
    ]
